controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_dual_arms_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_left_hand_controller
    joints:
      - link1
      - link11
      - link2
      - link22
      - link3
      - link33
      - link4
      - link44
      - link5
      - link51
      - link52
      - link53
  - name: fake_right_hand_controller
    joints:
      - Link1
      - Link11
      - Link2
      - Link22
      - Link3
      - Link33
      - Link4
      - Link44
      - Link5
      - Link51
      - Link52
      - Link53
  - name: fake_dual_hands_controller
    joints:
      - link1
      - link11
      - link2
      - link22
      - link3
      - link33
      - link4
      - link44
      - link5
      - link51
      - link52
      - link53
      - Link1
      - Link11
      - Link2
      - Link22
      - Link3
      - Link33
      - Link4
      - Link44
      - Link5
      - Link51
      - Link52
      - Link53
  - name: fake_dual_arms_with_hands_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - link1
      - link11
      - link2
      - link22
      - link3
      - link33
      - link4
      - link44
      - link5
      - link51
      - link52
      - link53
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
      - Link1
      - Link11
      - Link2
      - Link22
      - Link3
      - Link33
      - Link4
      - Link44
      - Link5
      - Link51
      - Link52
      - Link53