controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_1_joint
      - left_shoulder_2_joint
      - left_shoulder_3_joint
      - left_elbow_1_joint
      - left_elbow_2_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_1_joint
      - right_shoulder_2_joint
      - right_shoulder_3_joint
      - right_elbow_1_joint
      - right_elbow_2_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
  - name: fake_Empty_controller
    joints:
      []
  - name: fake_dual_arms_controller
    joints:
      - left_shoulder_1_joint
      - left_shoulder_2_joint
      - left_shoulder_3_joint
      - left_elbow_1_joint
      - left_elbow_2_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - right_shoulder_1_joint
      - right_shoulder_2_joint
      - right_shoulder_3_joint
      - right_elbow_1_joint
      - right_elbow_2_joint
      - right_wrist_1_joint
      - right_wrist_2_joint