<?xml version="1.0"?>

<robot xmlns:xacro="http://wiki.ros.org/xacro"
             name="human_hand_model" >


  <!-- Set up hyper-parameters -->
  <xacro:arg name="prefix" default="right" /> 
  <xacro:property name="palm_length" value="0.1" />
  <xacro:property name="palm_width" value="0.01" />
  <xacro:property name="palm_height" value="0.15" />  


  <!-- Just for visualiation -->
  <xacro:property name="finger_width" value="0.01" />
  <xacro:property name="finger_length" value="0.015" />


  <!-- Macro for three-link *FINGER* model -->
  <xacro:macro name="three_link_finger" params="prefix 
                                                parent
                                                origin_x origin_y origin_z
                                                DP_length DP_width DP_height 
                                                IP_length IP_width IP_height
                                                PP_length PP_width PP_height
                                                ">
    <!-- Proximal Phalange -->
    <link name="${prefix}_PP_link">  
      <visual>
        <origin xyz="0 0 ${PP_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${PP_width} ${PP_length} ${PP_height}" />
        </geometry>
        <material name="PaleGreen">
          <color rgba="0.596 0.984 0.596 1.0" />
        </material>
      </visual>
    </link>

    <!-- a virtual link -->
    <link name="${prefix}_virtual_link" />

    <!-- Intermediate Phalange -->
    <link name="${prefix}_IP_link">
      <visual>
        <origin xyz="0 0 ${IP_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${IP_width} ${IP_length} ${IP_height}" />
        </geometry>
        <material name="LightSkyBlue">
          <color rgba="0.529 0.808 0.980 1.0" />
        </material>
      </visual>
    </link>

    <!-- Distal Phalange -->
    <link name="${prefix}_DP_link">
      <visual>
        <origin xyz="0 0 ${DP_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${DP_width} ${DP_length} ${DP_height}" />
        </geometry>
        <material name="LightSalmon">
          <color rgba="1.0 0.627 0.478 1.0" />
        </material>
      </visual>
    </link>


    <!-- Metacarpophalangeal Joint, for abduction/adduction -->
    <joint name="${prefix}_MCP_abduction_joint" type="revolute">
      <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0" />
      <axis xyz="1 0 0" />
      <parent link="${parent}" />
      <child link="${prefix}_virtual_link" />
      <limit effort="100" velocity="10.0" lower="${-pi/18}" upper="${pi/18}" />
    </joint>

    <!-- Metacarpophalangeal Joint, for extension/flexion -->
    <joint name="${prefix}_MCP_flexion_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="${prefix}_virtual_link" />
      <child link="${prefix}_PP_link" />
      <limit effort="100" velocity="10.0" lower="0" upper="${pi/2}" />
    </joint>

    <!-- Proximal Interphalangeal Joint -->
    <joint name="${prefix}_PIP_joint" type="revolute">
      <origin xyz="0 0 ${PP_height}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="${prefix}_PP_link" />
      <child link="${prefix}_IP_link" />
      <limit effort="100" velocity="10.0" lower="0" upper="${pi/2}" />
    </joint>

    <!-- Distal Interphalangeal Joint -->
    <joint name="${prefix}_DIP_joint" type="revolute">
      <origin xyz="0 0 ${IP_height}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="${prefix}_IP_link" />
      <child link="${prefix}_DP_link" />
      <limit effort="100" velocity="10.0" lower="0" upper="${pi/2}" />
    </joint>

  </xacro:macro>



  <!-- Macro for three-link *THUMB* model -->
  <xacro:macro name="three_link_thumb" params="prefix 
                                                parent
                                                origin_x origin_y origin_z
                                                DP_length DP_width DP_height 
                                                IP_length IP_width IP_height
                                                PP_length PP_width PP_height
                                                ">

    <!-- virtual links -->
    <link name="${prefix}_virtual_link_1" />
    <link name="${prefix}_virtual_link_2" />

    <!-- Proximal Phalange -->
    <link name="${prefix}_PP_link">  
      <visual>
        <origin xyz="0 0 ${PP_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${PP_width} ${PP_length} ${PP_height}" />
        </geometry>
        <material name="PaleGreen">
          <color rgba="0.596 0.984 0.596 1.0" />
        </material>
      </visual>
    </link>

    <!-- Intermediate Phalange -->
    <link name="${prefix}_IP_link">
      <visual>
        <origin xyz="0 0 ${IP_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${IP_width} ${IP_length} ${IP_height}" />
        </geometry>
        <material name="LightSkyBlue">
          <color rgba="0.529 0.808 0.980 1.0" />
        </material>
      </visual>
    </link>

    <!-- Distal Phalange -->
    <link name="${prefix}_DP_link">
      <visual>
        <origin xyz="0 0 ${DP_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${DP_width} ${DP_length} ${DP_height}" />
        </geometry>
        <material name="LightSalmon">
          <color rgba="1.0 0.627 0.478 1.0" />
        </material>
      </visual>
    </link>


    <!-- Metacarpophalangeal Joint 1 -->
    <joint name="${prefix}_MCP_joint_1" type="revolute">
      <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0" />
      <axis xyz="-1 0 0" />
      <parent link="${parent}" />
      <child link="${prefix}_virtual_link_1" />
      <limit effort="100" velocity="10.0" lower="0.0" upper="${pi/9}" />
    </joint>

    <!-- Metacarpophalangeal Joint 2 -->
    <joint name="${prefix}_MCP_joint_2" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 -1" />
      <parent link="${prefix}_virtual_link_1" />
      <child link="${prefix}_PP_link" />
      <limit effort="100" velocity="10.0" lower="0" upper="${pi/1.8}" />
    </joint>

    <!-- Proximal Interphalangeal Joint 1 -->
    <joint name="${prefix}_PIP_joint_1" type="revolute">
      <origin xyz="0 0 ${PP_height}" rpy="0 0 0" />
      <axis xyz="1 0 0" />
      <parent link="${prefix}_PP_link" />
      <child link="${prefix}_virtual_link_2" />
      <limit effort="100" velocity="10.0" lower="0" upper="${pi/4}" />
    </joint>

    <!-- Proximal Interphalangeal Joint 2 -->
    <joint name="${prefix}_PIP_joint_2" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="${prefix}_virtual_link_2" />
      <child link="${prefix}_IP_link" />
      <limit effort="100" velocity="10.0" lower="0" upper="${pi/2}" />
    </joint>

    <!-- Distal Interphalangeal Joint -->
    <joint name="${prefix}_DIP_joint" type="revolute">
      <origin xyz="0 0 ${IP_height}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="${prefix}_IP_link" />
      <child link="${prefix}_DP_link" />
      <limit effort="100" velocity="10.0" lower="0" upper="${pi/2}" />
    </joint>

  </xacro:macro>



  <!-- Construct the hand model -->
  <link name="world" />

  <!-- Palm -->
  <link name="$(arg prefix)_palm">
    <visual>
      <origin xyz="0 0 ${palm_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${palm_width} ${palm_length} ${palm_height}" />
      </geometry>
      <material name="LightGold">
        <color rgba="0.933 0.867 0.510 1.0" />
      </material>
    </visual>
  </link>

  <joint name="$(arg prefix)_palm_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="world" />
    <child link="$(arg prefix)_palm" />
  </joint>


  <!-- Four fingers -->
  <xacro:three_link_finger prefix="$(arg prefix)_little_finger" parent="$(arg prefix)_palm"
                           origin_x="0.0" origin_y="${-palm_length/2+finger_length/2}" origin_z="${palm_height}"
                           DP_length="${finger_length}" DP_width="${finger_width}" DP_height="0.01"
                           IP_length="${finger_length}" IP_width="${finger_width}" IP_height="0.02"
                           PP_length="${finger_length}" PP_width="${finger_width}" PP_height="0.03" />

  <xacro:three_link_finger prefix="$(arg prefix)_ring_finger" parent="$(arg prefix)_palm"
                           origin_x="0.0" origin_y="${-finger_length/2-0.01}" origin_z="${palm_height}"
                           DP_length="${finger_length}" DP_width="${finger_width}" DP_height="0.02"
                           IP_length="${finger_length}" IP_width="${finger_width}" IP_height="0.03"
                           PP_length="${finger_length}" PP_width="${finger_width}" PP_height="0.04" />

  <xacro:three_link_finger prefix="$(arg prefix)_middle_finger" parent="$(arg prefix)_palm"
                           origin_x="0.0" origin_y="${finger_length/2 + 0.01}" origin_z="${palm_height}"
                           DP_length="${finger_length}" DP_width="${finger_width}" DP_height="0.021"
                           IP_length="${finger_length}" IP_width="${finger_width}" IP_height="0.032"
                           PP_length="${finger_length}" PP_width="${finger_width}" PP_height="0.043" />

  <xacro:three_link_finger prefix="$(arg prefix)_index_finger" parent="$(arg prefix)_palm"
                           origin_x="0.0" origin_y="${palm_length/2-finger_length/2}" origin_z="${palm_height}"
                           DP_length="${finger_length}" DP_width="${finger_width}" DP_height="0.02"
                           IP_length="${finger_length}" IP_width="${finger_width}" IP_height="0.03"
                           PP_length="${finger_length}" PP_width="${finger_width}" PP_height="0.04" />

  <!-- Thumb -->
  <xacro:three_link_thumb prefix="$(arg prefix)_thumb" parent="$(arg prefix)_palm"
                           origin_x="0.0" origin_y="${palm_length/2}" origin_z="0.0"
                           DP_length="${finger_length}" DP_width="${finger_width}" DP_height="0.02"
                           IP_length="${finger_length}" IP_width="${finger_width}" IP_height="0.03"
                           PP_length="${finger_length}" PP_width="${finger_width}" PP_height="0.05" />
 

</robot>





