<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="human_model">

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <legacyModeNS>true</legacyModeNS>
        </plugin>
    </gazebo>

    <xacro:include filename="$(find human_model)/urdf/arm.urdf.xacro"/>

    <!-- Human upperarm, forearm, hand size parameters -->
    <xacro:property name="arm_scale" value="1"/>
    <xacro:property name="upperarm_length" value="${0.2*arm_scale}"/>
    <xacro:property name="forearm_length" value="${0.23*arm_scale}"/>
    <xacro:property name="hand_length" value="${0.12*arm_scale}"/>
    <xacro:property name="shoulder_height" value="1.3"/>
    <xacro:property name="shoulder_width" value="0.54"/>

    <!-- World link-->
    <link name="world"/>

    <!-- Human model base -->
    <link name="human_base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
        </inertial>    
    </link>
    <joint name="human_base_fixed_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="human_base_link"/>
    </joint>

    <!-- Arms -->
    <xacro:arm prefix="left" parent="human_base_link" dir="-1"
                upperarm_length="${upperarm_length}"
                forearm_length="${forearm_length}"
                hand_length="${hand_length}" 
                shoulder_pos_x="0" shoulder_pos_y="${shoulder_width/2}" shoulder_pos_z="${shoulder_height}" />

    <xacro:arm prefix="right" parent="human_base_link" dir="1"
                upperarm_length="${upperarm_length}"
                forearm_length="${forearm_length}"
                hand_length="${hand_length}" 
                shoulder_pos_x="0" shoulder_pos_y="-${shoulder_width/2}" shoulder_pos_z="${shoulder_height}" />

    

</robot>    